export const SITE = {
  website: "https://sebwdo.me/",
  author: "Sebastian Wdowiarz",
  profile: "https://sebwdo.me/about",
  desc: "A minimal, responsive and SEO-friendly Astro blog theme.",
  title: "Sebastian Wdowiarz",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/satnaing/astro-paper/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "pl",
  timezone: "Europe/Warsaw",
} as const;
