export const SITE = {
  website: "https://codingathlete.com/",
  author: "Sebastian Wdowiarz",
  profile: "https://codingathlete.com/about",
  desc: "Software engineer and athlete. Python backends, APIs and data. CrossFit, HYROX, running, cycling.",
  title: "CodingAthlete",
  ogImage: "og.png",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Warsaw",
} as const;
